---
- name: Create New Directory Locally
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Create new directory
      file:
        path: "{{ lookup('env', 'PWD') }}/tesdir"
        state: directory

    - name: Display new directory creation status
      debug:
        msg: "Directory 'newdir' created successfully."

